# all queries constants and respective names
from . import queries_raw_code as qrc

queries_constants = [
    (qrc.ALL_UNITS, 'ALL_UNITS'), (qrc.SLA_OVER_TIME_ALL_UNITS, 'SLA_OVER_TIME_ALL_UNITS'),
    (qrc.RECENT_READINGS, 'RECENT_READINGS'), (qrc.DAILY_TRANSMISSIONS_INSTC_COMGAS23, 'DAILY_TRANSMISSIONS_INSTC_COMGAS23'),
    (qrc.DAILY_TRANSMISSIONS_LABC_COMGAS22, 'DAILY_TRANSMISSIONS_LABC_COMGAS22')
]